set nocompatible

scriptencoding utf-8


""
" ## Prepare
"
" ```
" curl -fLo ~/.cache/xvim/site/autoload/plug.vim --create-dirs https://raw.githubusercontent.com/junegunn/vim-plug/master/plug.vim
" ```
""

let &runtimepath = '~/.cache/xvim/site' . ',' . &runtimepath
"set packpath+=~/.cache/xvim/site

call plug#begin('~/.cache/xvim/plug')


	" ## https://github.com/Ntpeters/vim-better-whitespace
	Plug 'Ntpeters/vim-better-whitespace'

call plug#end()


let g:better_whitespace_enabled=1
let g:strip_whitespace_on_save=1
let g:strip_whitespace_confirm=0
let g:better_whitespace_ctermcolor='132'
"let g:better_whitespace_ctermcolor='132'
"https://github.com/morhetz/gruvbox
