set nocompatible

scriptencoding utf-8


" ## set hidden for [Switch Buffer] smooth
set hidden


" ## Switch Window
nnoremap <Tab> <C-w>w
nnoremap <BS> <C-w>W


" ## Switch Buffer
nnoremap <C-k> :bprevious<CR>
nnoremap <C-j> :bnext<CR>


" ## Switch TabPage
nnoremap <C-h> :tabprevious<CR>
nnoremap <C-l> :tabnext<CR>
