set nocompatible

scriptencoding utf-8

let &packpath = '~/.cache/xvim/site' . ',' . &packpath
"set packpath+=~/.cache/xvim/site

packadd! gruvbox

syntax enable

set background=dark

colorscheme gruvbox
