set nocompatible

scriptencoding utf-8


""
" ## Prepare
" ```
" mkdir -p ~/.cache/xvim/site/pack/themes/start
" cd ~/.cache/xvim/site/pack/themes/start
" git clone https://github.com/sickill/vim-monokai.git monokai
" ```
""

let &packpath = '~/.cache/xvim/site' . ',' . &packpath

packadd! monokai

syntax enable

set background=dark

colorscheme monokai
