set nocompatible

scriptencoding utf-8


set wildmenu
"set wildmode=longest:list,full
set wildmode=longest,full
"set wildmode=list:longest,full
"set wildmode=list:full
"set wildmode=list,full

"cnoremap <Left> <Space><BS><Left>
"cnoremap <Right> <Space><BS><Right>


"https://vi.stackexchange.com/questions/5029/key-mapping-that-will-invoke-the-wildmenu
"set wildcharm=<C-z>
"nnoremap <C-l> :buffer<Space><C-z>

set wildcharm=<C-o>
"nnoremap <C-l> :buffer<Space><C-o>
nnoremap <Space>bb :buffer<Space><C-o>

cnoremap <C-y> <Up>

if has('nvim')
  cnoremap <C-l> <Down><BS><C-o>
else
  cnoremap <C-l> <Down>
endif
