set nocompatible

scriptencoding utf-8


""
" ## Prepare
"
" ```
" curl -fLo ~/.cache/xvim/site/autoload/plug.vim --create-dirs https://raw.githubusercontent.com/junegunn/vim-plug/master/plug.vim
" ```
""

let &runtimepath = '~/.cache/xvim/site' . ',' . &runtimepath

call plug#begin('~/.cache/xvim/plug')


	" ## https://www.jianshu.com/p/aadce0fe9649
	" ## https://github.com/liuchengxu/space-vim-theme
	Plug 'liuchengxu/space-vim-theme'

	" ## https://github.com/sickill/vim-monokai
	Plug 'sickill/vim-monokai'

	" ## https://github.com/morhetz/gruvbox
	Plug 'morhetz/gruvbox'

	" ## https://github.com/joshdick/onedark.vim
	Plug 'joshdick/onedark.vim'

	" ## https://github.com/junegunn/seoul256.vim
	Plug 'junegunn/seoul256.vim'

call plug#end()


"set background=light
set background=dark

colorscheme gruvbox
