set nocompatible

scriptencoding utf-8


""
" ## Prepare
"
" ```
" curl -fLo ~/.cache/xvim/site/autoload/plug.vim --create-dirs https://raw.githubusercontent.com/junegunn/vim-plug/master/plug.vim
" ```
""

let &runtimepath = '~/.cache/xvim/site' . ',' . &runtimepath
"set packpath+=~/.cache/xvim/site

call plug#begin('~/.cache/xvim/plug')


	" ## https://github.com/liuchengxu/vim-clap
	"Plug 'liuchengxu/vim-clap'
	Plug 'liuchengxu/vim-clap', { 'do': { -> clap#installer#force_download() } }


call plug#end()

let g:clap_theme = 'material_design_dark'
