set nocompatible

scriptencoding utf-8


""
" ## Prepare
"
" ```
" curl -fLo ~/.cache/xvim/site/autoload/plug.vim --create-dirs https://raw.githubusercontent.com/junegunn/vim-plug/master/plug.vim
" ```
""

let &runtimepath = '~/.cache/xvim/site' . ',' . &runtimepath

call plug#begin('~/.cache/xvim/plug')


	" ## https://github.com/morhetz/gruvbox
	Plug 'morhetz/gruvbox'


call plug#end()


set background=light

colorscheme gruvbox
